# 中文预测的label

def get_labels():
    return ('-',
            '|',
            'e',
            't',
            'o',
            'i',
            'a',
            'n',
            's',
            'r',
            'h',
            'l',
            'd',
            'c',
            'u',
            'm',
            'p',
            'f',
            'g',
            'w',
            'y',
            'b',
            'v',
            'k',
            'x',
            'j',
            'q',
            'z')